export const transformers = [
  {
    name: "Optimus Prime",
    rarity: "legendary",
    chance: 5,
    image: "/images/drops/optimus.png",
  },
  {
    name: "Megatron",
    rarity: "legendary",
    chance: 5,
    image: "/images/drops/megatron.png",
  },
  {
    name: "Bumblebee",
    rarity: "epic",
    chance: 7,
    image: "/images/drops/bumblebee.webp",
  },
  {
    name: "Starscream",
    rarity: "epic",
    chance: 7,
    image: "/images/drops/starscream.png",
  },
  { name: "Jazz", rarity: "rare", chance: 10, image: "/images/drops/jazz.png" },
  {
    name: "Ironhide",
    rarity: "rare",
    chance: 10,
    image: "/images/drops/ironhide.png",
  },
  {
    name: "Ratchet",
    rarity: "rare",
    chance: 10,
    image: "/images/drops/ratchet.png",
  },
  {
    name: "Soundwave",
    rarity: "epic",
    chance: 7,
    image: "/images/drops/soundwave.webp",
  },
  {
    name: "Shockwave",
    rarity: "epic",
    chance: 7,
    image: "/images/drops/shockwave.png",
  },
  {
    name: "Grimlock",
    rarity: "legendary",
    chance: 5,
    image: "/images/drops/grimlock.png",
  },
  {
    name: "Arcee",
    rarity: "rare",
    chance: 10,
    image: "/images/drops/arcee.webp",
  },
  {
    name: "Wheeljack",
    rarity: "rare",
    chance: 10,
    image: "/images/drops/wheeljack.png",
  },
  {
    name: "Prowl",
    rarity: "common",
    chance: 8,
    image: "/images/drops/prowl.png",
  },
  {
    name: "Sideswipe",
    rarity: "common",
    chance: 8,
    image: "/images/drops/sideswipe.png",
  },
  {
    name: "Sunstreaker",
    rarity: "common",
    chance: 8,
    image: "/images/drops/sunstreaker.png",
  },
  {
    name: "Blurr",
    rarity: "common",
    chance: 8,
    image: "/images/drops/blurr.png",
  },
  { name: "Kup", rarity: "common", chance: 8, image: "/images/drops/kup.png" },
  {
    name: "Hot Rod",
    rarity: "epic",
    chance: 7,
    image: "/images/drops/hotrod.png",
  },
  {
    name: "Rodimus Prime",
    rarity: "legendary",
    chance: 5,
    image: "/images/drops/rodimus.png",
  },
  {
    name: "Ultra Magnus",
    rarity: "epic",
    chance: 7,
    image: "/images/drops/ultramagnus.webp",
  },
];
